name: devcontainer tester

on:
  push:
    paths:
      - '/.devcontainer/**.json'
jobs:
  devcontainerDryRun:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/coder/envbuilder:latest
    steps:
      - uses: actions/checkout@v4
      - name : Devcontainer dry run
        run : echo "Dry run succesful"
