name: devcontainer tester

on:
  push:
    paths:
      - '.devcontainer/**'
jobs:
  devcontainerDryRun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout devcontainer.json
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and run dev container
        uses: devcontainers/ci@v0.3
        with:
          devcontainerPath: .devcontainer
          imageName: captaionstinkrat/devcontainerdryrun
          imageTag : ${{ github.sha }}
      - name : Devcontainer dry run
        run : echo "Dry run succesful"
      - name: Push image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            captainstinkrat/devcontainerdryrun:latest
            captainstinkrat/devcontainerdryrun:${{ github.sha }}
  devcontainerScriptBuilding:
    runs-on: ubuntu-latest
    needs: devcontainerDryRun
    steps:
      - name: Running commands in Dev Container
        uses: devcontainers/ci/actions/container-run@v0.3
        with:
          imageName: devcontainerdryrun
          runArgs: |
            -v ${{ github.workspace }}:/workspace
          command: |
            
            python3 -m venv venv
            source venv/bin/activate
            pip install -r /workspace/devcontainers/requirements.txt && python3 /workspace/devcontainers/test.py
      
